name: ci-cd

on:
  push:
  pull_request:

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

        # Authenticate with GitHub using the PAT token
        git config --global credential.helper store
        echo "https://github.com/${GITHUB_REPOSITORY}.git ${PAT_TOKEN}" >> ~/.git-credentials

        # Set up a GitHub token to avoid rate-limiting issues (optional but recommended)
        poetry config pypi-token.pypi ${{ secrets.GITHUB_TOKEN }}

        # Install dependencies using Poetry
        poetry install

    - name: Print current directory
      run: |
        pwd
        ls -la

    - name: Run tests
      run: |
        cd ./src/tests/
        python -m unittest goblin_test.py
