name: ci-cd

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        echo PAT_TOKEN

    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up Git authentication
      run: git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Install dependencies
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install .

    - name: Print current directory
      run: |
        pwd
        ls -la

    - name: Run tests
      run: |
        cd ./src/tests/
        python -m unittest goblin_test.py 
